### ISSUE TITLE
Coin Control issue

### ISSUE THREAD

**Issue by anonymousventures** [MonetaOfficial/moneta#4]
![bug](https://cloud.githubusercontent.com/assets/5482646/11956662/08cd5448-a8bc-11e5-9206-181dd21f97a2.png)

 Macht from Slack: "I noticed that when sending using coin control, the transaction fee shows zero. Then asks for you to spend the transaction fee."

**Comment by nopslide** [comment]
It has been fixed with commit/b2b0ecfa11a16f95fb73f285f4641958902660c3.
